### ISSUE TITLE
Suggested additional setup steps

### ISSUE THREAD

**Issue by colonelsalt** [pr0g/opengl-sdl#1]
Really cool project! Took me a few extra steps not mentioned in the readme get it to actually build and run. Might be worth adding if others want to try in future (don't know if these steps are obvious, but took me a little tinkering to work out):

1. Had to run all setup via Developer PowerShell for VS, or it would not pick up the MSVC compiler
2. Run configure.bat
3. Go in SDL folder and run `cmake -B build`
4. Open VS solution for SDL and build it
5. Set environment variable `SDL2_DIR` to `./third-party/sdl/build/cmake` (or CMake will not pick up SDL)
6. Run `cmake -B build` in root folder
7. Open generated VS solution file, and make sure `AS_PRECISION_FLOAT/AS_PRECISION_DOUBLE` and `AS_COL_MAJOR/AS_ROW_MAJOR` are defined for the build
8. Set opengl-sdl as startup project; build and run

(This is on a Windows 11 machine, building for VS 2022, for the record.)

**Comment by pr0g** [comment]
Hey @colonelsalt!

Thanks very much for checking out the repo and the great feedback. I'll see if I can update the README with more concrete steps soon.

One neat thing I added recently which should make the whole process simpler is the `SUPERBUILD` option.

With this, the third-party dependencies should be built automatically without compiling SDL2 separately. I have more detailed steps in a similar vein as part of this repo - https://github.com/pr0g/sdl-bgfx-imgui-starter that could be useful.

Would you be able to check if you have the latest commit and have the `SUPERBUILD` option (it should be enabled in the `configure.bat/sh` script)?

Also if you're not using the `SUPERBUILD` option, instead of setting `SDL2_DIR` you should be able to use `-DCMAKE_PREFIX_PATH` to let CMake know where to look for the third-party libraries, something like...

```bash
cmake -B build-G "Visual Studio 17 2022"
-DCMAKE_PREFIX_PATH=%cd%/third-party/sdl/build ^
-DAS_COL_MAJOR=ON -DAS_PRECISION_FLOAT=ON
``` 

Should work...

Also if you want to use a regular terminal you can run `VsDevCmd.bat` (see [here](https://learn.microsoft.com/en-us/visualstudio/ide/reference/command-prompt-powershell?view=vs-2022#developer-command-prompt) for more info).

I'll make some updates likely at the weekend and let you know and will close the issue after that. Thanks again!

**Comment by colonelsalt** [comment]
Appreciate the detailed response and the extra resources! Forgive me for being a CMake newb: looks like my error was assuming that the target CMake output would be a Visual Studio solution by default, but actually `ninja` is meant to build the final executable?

Ninja proved slightly non-trivial to get working from first few cursory attempts, but I'm sure with a little more time I can work it out. For the time being, just dropping the `-G Ninja` option from `configure.bat` so it generates for VS2022 instead does indeed configure everything in one go.

Thanks, and feel free to close.

**Comment by pr0g** [comment]
No problem at all! Lol that's quite alright, I still don't feel like a CMake aficionado either 🙈 There's a lot I have no clue about, I just really like the simple bits that make developing in C++ easier.

I think I defaulted to Ninja purely because it's a single-config generator as opposed to a multi-config generator and works on Windows, Mac, and Linux in the same way. Visual Studio is a multi-config generator (so when you configure/generate you don't specify the build type using `-DCMAKE_BUILD_TYPE`, instead when you invoke `cmake --build <build-folder>` you pass `--config <build-type>` (e.g. `--config Release`). This is useful but makes things different across platforms annoyingly. Interestingly Ninja ships with Visual Studio and if you run `VsDevCmd.bat` (or open the VS Command Prompt) it'll get added to your path.

I'll definitely try and find some time this weekend to update the README with a bit more info and will close this issue once that's done 🙂 

Thanks!

**Comment by pr0g** [comment]
Updated README to include a bit more info, closing this issue for now (let me know if there's anything else that would be useful to add :+1:).
